version: '3.7'
services:

  backend:
    build: backend
    ports:
      - "${BACKEND_HOST_PORT}8000"
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: ${RUNSERVER:-/bin/bash}
    networks:
      - backend-network
    restart: ${DOCKER_RESTART:-no}

  proxy:
    build: proxy
    ports:
      - "${PROXY_HOST_PORT}80"
    volumes: 
      - ./frontend:/app
    depends_on: 
      - backend
    environment:
      VIRTUAL_HOST: xyzcreditos.lfvilella.com
      VIRTUAL_HOST_ALIAS: xyzcreditos.lfvilella.com,www.xyzcreditos.lfvilella.com
      LETSENCRYPT_HOST: xyzcreditos.lfvilella.com,www.xyzcreditos.lfvilella.com
      LETSENCRYPT_EMAIL: vilella.luisfelipe+xyzcreditos.lfvilella.com@gmail.com
    links: 
      - backend:backend_api
    networks:
      - backend-network
      - nginx-gateway
    restart: ${DOCKER_RESTART:-no}

networks:
  backend-network:
  nginx-gateway:
      external:
          name: nginx-gateway