version: '3.7'
services:

  backend:
    build: backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/bash

  proxy:
    build: proxy
    ports:
      - "80:80"
    volumes: 
      - ./frontend:/app
    depends_on: 
      - backend
    links: 
      - backend:backend_api