###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
      
      ###############################
      # Install Python Requirements #
      ###############################
      - name: Install Python Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements-test.txt
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v2.0.0
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_YAML: true
          VALIDATE_JSON: false
          VALIDATE_XML: false
          VALIDATE_MD: false
          VALIDATE_BASH: false
          VALIDATE_PERL: false
          VALIDATE_PYTHON: true
          VALIDATE_RUBY: false
          VALIDATE_COFFEE: false
          VALIDATE_ANSIBLE: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_DOCKER: true
          VALIDATE_GO: false
          VALIDATE_TERRAFORM: false
